### ISSUE TITLE
error trying to create 'PutBucketNotificationConfiguration'

### ISSUE THREAD

**Issue by curras** [pjodouin/ansible-lambda#5]
I've looked at your examples and code and I'm unable to diagnosis the issue. I'm not sure if this a documentation bug or if I'm missing something obvious. the lambda function is created and I get the following error when it tries to execute the notification configuration. 

error: "module_name": "lambda_s3_event"}, "msg": "Error creating s3_lambda_event: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations"}

```---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  - name: create function
    lambda:
      state: "{{ state | default('present') }}"
      type: code
      function_name: test
      runtime: java8
      code:
        s3_bucket: {{ bucket }}
		s3_key: {{ s3Key }}
      timeout: 3
      handler: {{ lambda.handler }}
      role: {{ lambda.role }}
      publish: True
      version: 4
      source_arn: {{ source.arn }}
  - name: display stuff
    debug: var=results


- hosts: localhost
  gather_facts: no
  vars:
    state: present
    bucket: {{ bucket }}
  tasks:
  - name: add s3 event notifications that trigger a lambda function
    lambda_s3_event:
      state: "{{ state | default('present') }}"
      bucket: "{{ bucket }}"
      lambda_function_configurations:
      - id: test
        lambda_function_arn: {{ lambda.function.arn }}
        events: [ 's3:ObjectCreated:*' ]
  - name: display stuff
    debug: var=results```

**Comment by pjodouin** [comment]
I suspect lambda_function_arn is pointing to a version/alias that does not exist.  I tried applying an event using an invalid version and got the same error.  However, the AWS API and console are buggy with respect to lambda versions.  If you start with the console, you cannot specify an alias or version for your s3 bucket event.  And I've discovered a few other anomalies. I recommend not using an explicit version for now and just use $LATEST.  

Also, I noticed that you have "version: 4" in your lambda task--this will not work with that module but should with the idempotent one I am currently writing.

Hope this helps.

**Comment by pjodouin** [comment]
OK, found and fixed a bug in the "policy" resource code.  And until the new version of my lambda module is fully functional, this is what you need to add after creating the function but before adding the s3 event:

```
---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  - name: add lambda permission
    lambda:
      state: "{{ state | default('present') }}"
      type: policy
      function_name: myFuntionName
      statement_id: "{{ some_unique_id }}"
      action: lambda:InvokeFunction
      source_arn: arn:aws:s3:::myBucketName
      principal: s3.amazonaws.com
      qualifier: '2'
```

Where **qualifier** can be an alias or version number.
